services:
  split-service:
    image: docker.io/hashicorp/http-echo:latest
    command: ["-listen=:8000", "-text=split-service stub"]
    expose:
      - "8000"

  bookmarks-service:
    image: docker.io/hashicorp/http-echo:latest
    command: ["-listen=:8000", "-text=bookmarks-service stub"]
    expose:
      - "8000"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Containerfile
    ports:
      - "8080:80"
    depends_on:
      - bookmarks-service
      - split-service
    profiles:
      - integration

  test:
    build:
      context: .
      dockerfile: tests/Containerfile
    profiles: 
      - integration
    depends_on:
      - api-gateway
      - bookmarks-service
      - split-service
    volumes:
      - ./:/app:Z
    working_dir: /app
    command: 
      - "--maxfail=1"
      - "--disable-warnings"
      - "tests/integration/test_api_gateway.py"
