FROM python:3-slim-bookworm as base

WORKDIR /tests

COPY podman/tests/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM base as test
COPY tests/ tests/

ENTRYPOINT ["pytest", "-q", "--disable-warnings", "--maxfail=1"]
