name: build_push
on:
  push:
    branches:
      - build
jobs:
  podman:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v4
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
      -
        name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push split-pdf-bookmarks
        uses: docker/build-push-action@v6
        with:
          context: app
          file: podman/Containerfile
          push: true
          tags: docker.io/${{ vars.DOCKER_USERNAME }}/split-pdf-bookmarks:latest
